### ISSUE TITLE
font-lock-comment-face breaks company

### ISSUE THREAD

**Issue by nree** [emacs-typescript/typescript.el#115]
```elisp
(custom-set-faces
 '(font-lock-comment-face ((t (:family "Arial"))))
 '(font-lock-comment-delimiter-face ((t (:family "Arial")))))
```
This breaks alignment on company autocomplete suggestions for me for some reason...

Font chose doesn't matter, and the comment-delimiter-face doesn't matter.

Happens in js2-mode too but not that often. Won't happen if the suggestions are short (doesn't have scrolling). Won't happen in elisp. 

I have a pretty simple company, tide, typescript setup (pretty much default configs).

Tried emacs-27.0.50-snapshot-2019-09-18-x86_64 & 26.3 for win10. 

Also got rid of my setup, cloned spacemacs develop branch, chose vim / minimal setup. Installed typescript & auto-completion layers. Copy pasted my font-lock code into  dotspacemacs/user-config. Still same results there too.

**Comment by josteink** [comment]
First off: Autocomplete is provide by [tide](https://github.com/ananthakumaran/tide). Tide-related issues should be filed there.

Isn't Arial a non fixed-width font? Doesn't company rely on fixed width output to ensure "aligned" columns when adding additional columns besides just the member-name?

What happens if you use another fixed-width font instead? Does that have issues?

I'm honestly not sure if this is the fault of tide *or* company-mode. Either way I'm closing the issue in this repo, as off-topic.

Please re-open in relevant repo!

**Comment by nree** [comment]
Yes you're right my apologies. I wasn't sure where to bring this up. 
But thank you for your reply. It gave me a better understanding of the issue. 
I had tried different fonts even monospace ones with same result so that threw me off. But your reply helped me better understand and I realize monospace will break too if it isn't "aligned" as you mentioned with the face company was using.

I don't wish to keep this issue going, I just wanted to tell you thanks.
