### ISSUE TITLE
Incompatibility with smartparens (wrap in quotes)

### ISSUE THREAD

**Issue by raeffu** [emacs-typescript/typescript.el#118]
With smartparens you can select text, then write `"` which will wrap the selected word/text in quotes 
 (like so: `"foobar"`). The commit https://github.com/emacs-typescript/typescript.el/commit/f20103a4487a404d11521305db63f550d9eb3fe1 breaks this functionality. The buffer is then totally f**ked up, even undo doesn't work correctly. `typescript-mode` is the only mode in my setup that has this problem. To reproduce this problem installing the newest version of `smartparens 20191015.1754` and `typescript-mode 20191025.1425` from melpa should work. Also `Emacs 26.3`.

Hope you understand what I mean. If you need more info don't hesitate to ask.

Thx for this awesome mode! ❤️

**Comment by zeusdeux** [comment]
The same applies to calling `typescript-insert-and-indent` (bound to `(`, etc) when `pending-delete-mode` is enabled in a `typescript-mode` buffer.

**Comment by PenguinToast** [comment]
This seems related to https://github.com/emacs-typescript/typescript.el/commit/f20103a4487a404d11521305db63f550d9eb3fe1 - undoing the changes from this commit fixes this issue locally for me.

**Comment by josteink** [comment]
@elibarzilay: This change was introduced by you. Would you care looking into it? :smiley:

**Comment by lddubeau** [comment]
@josteink I have a partial solution in [this branch](https://github.com/emacs-typescript/typescript.el/tree/smartparens-compatibility). It takes care of everything except the issue with the quotes.

As far as the quotes are concerned. Here are my thoughts:

1. First of all, looking at the code of smartparens and delete-selection, I"m seeing a lot of code that depends on things being "just so". Smartparens in particular is quite demanding. It goes even as far as sorting hooks by priority to ensure that its logic works! If things are not "just so" then the logic falls apart.

2. It seems to me the work done by `typescript-insert-and-autoconvert-to-template` is incompatible with the use of smartparens. The scenario for `typescript-insert-and-autoconvert-to-template` was I start typing a string using " or ', then while typing it I decide it is going to be a template. *When I close the string*, the mode looks over the string to see whether it has expression expansions in it and if so it converts it to a template. With smartparens-mode on, the string is closed as soon as it is opened so there's no opportunity to perform a meaningful check on the string when the string is closed. I could think of a different implementation that would check the string after the caret is moved outside the string, and this would be useful with smartparens too, but I don't have the interest right now to investigate this approach.

   Perhaps the solution here would be to change the `typescript-autoconvert-to-template-flag` so that if it is not set, then no remapping to `typescript-insert-and-autoconvert-to-template` is done. The downside is that turning the flag on or off will require restarting the mode in the current buffer prior to the change taking effect. (Whereas now changing the flag has immediate effect and does not require restarting the mode, which I quite like.)

3. There may be a way to rework the implementation `typescript-insert-and-autoconvert-to-template` to keep it always bound, and keep the flag have immediate effect but as I wrote in my first point a lot of things have to be "just so" to work. I'm still investigating... but I don't know how much more patience I have to figure out how to avoid conflicts among the modes.

**Comment by elibarzilay** [comment]
1. @zeusdeux -- is that with `pending-delete-mode` and without anything
   else?  (I'd be surprised since that's just an alias for
   `delete-selection-mode` which is where I saw the problem.)

2. @lddubeau -- using built-in functionality sounds like a good idea.

3. I had a brief look at smartparens, and was horrified that so much
   code is needed for functionality that is mostly part of Emacs anyway.
   Not only that, @lddubeau's mention of sorting hooks, and the many
   function that it modifies via advices make it seem like a fragile
   package.

   So I'd suspect that the problem starts there, since my change is
   really using standard Emacs properties, and IIRC, someone else
   besides me verified that there was a bug.

**Comment by lddubeau** [comment]
@PenguinToast @zeusdeux @raeffu Can you try the fix in #124 and let me know whether you still have problems after that fix is applied?

**Comment by raeffu** [comment]
@lddubeau Fix #124 solves the problem for me! 👍

**Comment by zeusdeux** [comment]
@lddubeau Can confirm #124 works for my use case as well. Thanks!

**Comment by lddubeau** [comment]
@raeffu @zeusdeux  Thanks for the beedback. The PR has been merged.

**Comment by zeusdeux** [comment]
@lddubeau Brilliant! Thanks! I'll update next week once it's on melpa! ^_^
