### ISSUE TITLE
Make typescript-mode compatible with mmm-mode

### ISSUE THREAD

**Issue by Jevri** [emacs-typescript/typescript.el#128]
The functions conserned with parsing call widen. This makes makes it unable to parse properly when used with mmm-mode.

**Comment by lddubeau** [comment]
In principle, being able to work fine with `mmm-mode` would be a valuable feature.

So we need someone who knows `mmm-mode` well enough to step up and implement this change. (And that person is not me because I do not use `mmm-mode`.) Merely removing the calls to `widen` won't do it. This [email](https://lists.gnu.org/archive/html/emacs-devel/2017-12/msg00321.html) mentions documentation for major modes to follow to work well with `mmm-mode`.

**Comment by lddubeau** [comment]
I've moved your title into the first comment and edited the title to reflect better what the stakes are. Dealing with `widen` is probably just *one* aspect of compatibility with `mmm-mode`.

**Comment by josteink** [comment]
> So we need someone who knows mmm-mode well enough to step up and implement this change

Agreed. And it's not me either.

How about you, @Jevri ?

**Comment by Jevri** [comment]
I honestly do not know much about either, other then it did not work because typescript mode tried to parse everything

**Comment by Jevri** [comment]
I might investigate a bit though

**Comment by Jevri** [comment]
I think this was actually a bug in Vue mode. The solution in the comments [here](https://github.com/AdamNiederer/vue-mode/issues/74) fixed my issue. Sorry for the trouble :)
