### ISSUE TITLE
Support arrow functions

### ISSUE THREAD

**Issue by TatriX** [emacs-typescript/typescript.el#18]
There is no support for syntax highlighting of the arrow function formal parameters, `beginning-of-defun` etc.

**Comment by lddubeau** [comment]
I'm closing this due to the lack of an actual case illustrating the problem. I'll gladly reopen once a case other people can use to reproduce the problem is added to this issue. I use `typescript-mode` day in and day out and don't recall a specific problem with highlighting arrow functions. Maybe it's been fixed while fixing another problem... hard to tell without a case.
