### ISSUE TITLE
Use prettier for formatting?

### ISSUE THREAD

**Issue by nspaeth** [emacs-typescript/typescript.el#39]
Now that prettier/prettier#13 supports typescript, would it make sense to offload formatting to that? It seems to be gaining traction as a defacto standard.

**Comment by josteink** [comment]
If you want pretty formatting, the recommended approach is to use [tide](https://github.com/ananthakumaran/tide).

By default, tide uses `tsserver` to format the code on save, giving you the standard formatting which TypeScript-code should adhere to by convention.

Is there anything else prettier could give us, that this doesn't already provide?

**Comment by josteink** [comment]
To add to my former comment, I've never heard of prettier before now, and I honestly would like to keep the list of dependencies for Emacs typescript-development as short as possible.

Right now a "full stack" requires the following:

- Emacs
- typescript.el
- tide (which bundles tsserver)
- nodejs (to run tsserver)

Despite this list of dependencies, and to my great surprise, this seems to work pretty seamless, consistent and well across all platforms I've tested it (even on Windows!).

I'd like to keep it like that, and adding more tools to the chain really has to do *wonderful* things to justify the risk :)

**Comment by lddubeau** [comment]
I'm going to close this. As usual, if there's a substantial argument to be made in favor of the feature proposed here, we can reopen.

**Comment by lddubeau** [comment]
I've tried prettier earlier today and immediately uninstalled it. 

I have a few reflections about "support for prettier" in the context of this mode.

First, right now, it looks like if anyone wants support for it, **they'll have to step up to the plate themselves** and provide a quality PR (substantially tested) for it.

I can see two ways "support for prettier" could potentially apply to this mode:

1. Support for running prettier on files automatically or manually. **In my opinion this functionality does not belong to this mode.** That's general Emacs "run-on-save" functionality, or something to trigger through linter runs. Linter runs are handled by `flycheck`, not this mode.

2. Modify the indentation code of this mode so that its indentation naturally matches the one that prettier wants. This is where I suppose an argument could be made that `typescript-mode` should have a configuration option allowing the selection of different indentation algorithms. As I said above, someone would have to step up to the plate to make this reality.
